### ISSUE TITLE
Requests HT / NT

### ISSUE THREAD

**Issue by GodHunter** [hdering/homematic_verbrauchszaehler#12]
Hey, 

erstmal vielen Dank für das Script. Das hilft mir schon sehr den Verbrauch unserer Wärmepumpe ordentlich zu protokollieren.

Wo wir dann schon beim Thema wären, die Wärmepumpe wird via HT / NT Zähler gezählt, ich weiß das das nen riesen Unterschied zu normalen Zählern macht, aber evtl. hast du ja Mal Zeit und Lust sowas umzusetzen.

**Comment by hdering** [comment]
Hi GodHunter,

ich kenne mich leider nicht damit aus. Was bedeutet HT / NT?
Im Prinzip müsstest du dir ein Script schreiben was HT / NT Zähler in Wh umrechnet. Und diesen eigenen Datenpunkt vom Script zählen lassen.
