### ISSUE TITLE
Pushover

### ISSUE THREAD

**Issue by smooty1970** [hdering/homematic_verbrauchszaehler#13]
Hallo.

Erst einmal Danke für das tolle Script. Generell funktioniert es. Wie kann denn Pushover zum Versenden von Messages verwendet werden?

Danke

**Comment by hdering** [comment]
Hi smooty1970,

in Zeile 71/72 kannst du einen Pushoverbefehl einbauen, dann wirst du auch bei relevanten Meldungen benachrichtigt.

Hier gibts Beispiele dazu: 
https://github.com/ioBroker/ioBroker.pushover#usage
