### ISSUE TITLE
Deklarationsfehler und Syntax Fehler korrigieren

### ISSUE THREAD

**Issue by Marty56** [hdering/homematic_verbrauchszaehler#17]
Ich habe versucht, dass Script zu nutzen und sehe einige Syntax und Deklarationsfehler.

z.B. 
        var instance
        newdate
        grundpreis_tag      = _grundpreis;
        grundpreis_woche    = _grundpreis * 7;
        grundpreis_monat    = _grundpreis * 30; 
        grundpreis_quartal  = _grundpreis * 90;
        grundpreis_jahr     = _grundpreis * 365;

        _unit = default_unit;
        _unit_kilo = default_unit_kilo;

Nach Korrektur scheint das Script zu laufen.

**Comment by hdering** [comment]
Hi Marty56,

ist das noch aktuell?
wo hattest du Deklarationsfehler gesehen?

**Comment by Marty56** [comment]
Ich kann mich nicht mehr daran erinnern und nutze das Script auch nicht mehr.
