### ISSUE TITLE
Welcher benutzerdefinierte Datenpunkt muss eingegeben werden?

### ISSUE THREAD

**Issue by wintuxx** [hdering/homematic_verbrauchszaehler#19]
Hallo zusammen,

vielleicht eine sehr dumme Frage. Muss man die Datenpunkte für die Leistung (W) oder Verbrauch angebeben (kWh)?

**Comment by hdering** [comment]
Hi wintuxx,

da solltest du den Verbrauch angegeben. Bei Homematic ist es Wh.
