### ISSUE TITLE
Tagesverbrauch wird nicht gespeichert

### ISSUE THREAD

**Issue by DutchmanNL** [hdering/homematic_verbrauchszaehler#6]
Script 1:1 übernommen und datenpunkte Manuel eingesetzt, nur die kumulierten werte werden übertragen alle anderen beiden lehr

Datenpunkte:

`
var eigeneDatenpunkte = [
    // Beispiel:
    // ['Datenpunkt', 'Aliasname', 'Einheit' ],
    
    // [ 'hm-rpc.2.NEQ0861663.1.ENERGY_COUNTER', 'Stromzaehler:1.ENERGY_COUNTER' ],
    // [ 'javascript.1.MeinePower', 'MeinSonoff' ],
    // [ 'javascript.1.MeinePower2', 'Sonoff.MeinZweiterSonoff' ],
    [ 'smartmeter.0.1-0:1_8_2.value', 'Stroom_Afname_piek', 'kWh' ],
    [ 'smartmeter.0.1-0:1_8_1.value', 'Stroom_Afname_Dal', 'kWh' ],
    [ 'smartmeter.0.1-0:2_8_2.value', 'Stroom_Levering_Piek', 'kWh' ],
    [ 'smartmeter.0.1-0:2_8_1.value', 'Stroom_Levering_Dal', 'kWh' ],
    [ 'smartmeter.0.0-1:24_3_0.value7', 'Gasverbruik', 'm3' ],
];
`

Wert aus dem Zähler:

![screen shot 2018-04-11 at 20 10 25](https://user-images.githubusercontent.com/7318445/38635032-71cf378c-3dc4-11e8-8a46-a9c1807fe4ab.png)

Werte als Ausgabe vom script:

![screen shot 2018-04-11 at 20 11 51](https://user-images.githubusercontent.com/7318445/38635094-975e1c20-3dc4-11e8-9ac1-0afd1eff76c5.png)

**Comment by hdering** [comment]
Lass das Skript mal einen Tag laufen bzw. wenn der Tageswechsel stattfindet (0:00 Uhr), dann wird der Wert gefüllt.

**Comment by DutchmanNL** [comment]
wird der tageswert nicht durchgängig geschrieben ? Ich meine den "seit tagesbegin" (falscher screenshot hier der richtige)

![screen shot 2018-04-11 at 20 17 54](https://user-images.githubusercontent.com/7318445/38635398-8089dbdc-3dc5-11e8-990e-1931309a816a.png)

**Comment by DutchmanNL** [comment]
ok deutlich, daraus schliesse ich das das script davon ausgeht das die werte in watt übergeben werden in meinen zählen sind es aber bereits Kwh werte.

Stimmt das ? wen ja werde ich das ändern und konfigurierbar machen mit einer variable und einen pull request erstellen.

**Comment by hdering** [comment]
Ja stimmt. Er rechnet mit Wh (kumulierter Wert). Der Rest wird in kWh umgerechnet.

**Comment by DutchmanNL** [comment]
ok also, nur zur Sicherheit, da mein Messgerät bereits die werte in KWH hergibt ist diese Umrechnung nicht nötig. (siehe screenshot)
wen ich dan die / 1000 Berechnung an de 2 stellen im script entferne  mache wird die Ausgabe korrekt sein.

Sorry der doppelte nachfrage aber das geht schneller als das ganze script durch zu suchen :)
Ich werde das dan auch als pull request anbieten sind bestimmt mehr die das gebrauch können (per variable auf wh/kw wählen

**Comment by hdering** [comment]
Ja stimmt. Zeile 356 und 477 muss die "/ 1000" weg. Ich baue das dann auch in das jetzige Skript ein.

**Comment by hdering** [comment]
mit Version 1.3.0 ist es nun möglich, die Umrechnung nach kWh zu deaktivieren.

**Comment by DutchmanNL** [comment]
hmm, leider auch heute keine werte in Verbrauch seit Tagesbeginn (Stroom_Afname_piek) siehe screenshot
(tagesbegin wurde geschrieben:

![screen shot 2018-04-12 at 13 02 41](https://user-images.githubusercontent.com/7318445/38673522-d82f98e0-3e51-11e8-8dca-5b7401b1fe8e.png)
