### ISSUE TITLE
var enable_Grundpreis_einberechnen = true oder var enable_Grundpreis = true

### ISSUE THREAD

**Issue by pmueller99** [hdering/homematic_verbrauchszaehler#7]
Hallo hdering,

vielen Dank für die tolle neue Version. Ich denke, in Zeile 32 muss es:
var enable_Grundpreis = true;

statt

var enable_Grundpreis_einberechnen = true;

heissen, oder?

Kannst Du mir noch sagen, wie man den Pfad in der Instanz von Strom in Verbrauchszaehler umbenennen kann?

Beste Grüße
Peer

**Comment by hdering** [comment]
Vielen Dank für den Hinweis, hab ich geändert.

**Comment by DutchmanNL** [comment]
> Kannst Du mir noch sagen, wie man den Pfad in der Instanz von Strom in Verbrauchszaehler umbenennen kann?

das geht nicht so einfach dazu muss man die iObroker JSON datei ändern. Würde empfehlen für diejenigen die das script bereits laufen haben im script Verbrauchszähler in Strom zu ändern

**Comment by hdering** [comment]
Tatsächlich export -> ändern -> import auch nicht. Zwar werden die Objecte eingebaut, aber die Werte fehlen...
