### ISSUE TITLE
Verbrauch seit tagesbegin wird nicht geschrieben, bleibt 0

### ISSUE THREAD

**Issue by DutchmanNL** [hdering/homematic_verbrauchszaehler#9]
Situation:

- script läuft seit 2 tagen
- kumulierter wert wird ständig erneuert
- Zählerstand tagesbegin wird um 12 Uhr gefüllt
![screen shot 2018-04-13 at 09 56 42](https://user-images.githubusercontent.com/7318445/38723344-0e426b7e-3f01-11e8-82c5-6b473d93cf33.png)
- verbrauch seit tagesbeginn bekommt um 12 Uhr den wert 0 und danach nichts mehr
![screen shot 2018-04-13 at 09 56 52](https://user-images.githubusercontent.com/7318445/38723372-29f99d4c-3f01-11e8-833e-55e556eb83e6.png)

**Comment by hdering** [comment]
Meinst du mit 12Uhr "12:00 Uhr" oder "24:00 Uhr" ?

Das Verhalten ist richtig.
Um 0:00 Uhr wird der Zählerstand von kumuliert nach Tag kopiert.
Um 0:00 Uhr wird der Verbrauch bei Tag durchrotiert, zurückgesetzt und wieder neu hochgezählt bis es wieder 0:00 Uhr.

Wird bei dir der Tagesverbrauch jetzt, nach 0:00 Uhr, nicht mehr gefüllt?

**Comment by DutchmanNL** [comment]
> Wird bei dir der Tagesverbrauch jetzt, nach 0:00 Uhr, nicht mehr gefüllt?

genau das ist leider der fall, der tagesverbraucht mit dem wert "Verbrauch seit Tagesbeginn" bleibt auf 0.
Ich sehe an dem Objekt das er genau um 00:00:00 den wert 0 aus dem script bekommen hat und danach tut sich nichts.

**Comment by DutchmanNL** [comment]
Auch nach 3 Tagen selbe Situation

![Image](https://i.imgur.com/tsVv4MJ.jpg)

**Comment by hdering** [comment]
Werden im Ordner Kosten Werte geschrieben?

Lass Mal die Console offen. Eigentlich müsste irgendeine Fehlermeldung zusehen sein.

Am 14. April 2018 09:54:29 MESZ schrieb Dutchman <notifications@github.com>:
>Auch nach 3 Tagen selbe Situation
>
>![Image](https://i.imgur.com/tsVv4MJ.jpg)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hdering/homematic_verbrauchszaehler/issues/9#issuecomment-381311520

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DutchmanNL** [comment]
Hi, nein Kosten werden auch nicht geschrieben.
Im Log sehe ich keine Fehler ausser eventuell device Name / ID = NULL

![Image](https://i.imgur.com/Uiy27Cr.jpg)

**Comment by hdering** [comment]
Hast du einen Arbeitspreis / Grundpreis eingetragen?
in: Strom.Preis.aktuell.Arbeitspreis
Strom.Preis.aktuell.Grundpreis

**Comment by hdering** [comment]
Auf was steht die Variable enable_unterschiedlichePreise?
True oder false?

Am 15. April 2018 00:23:08 MESZ schrieb Dutchman <notifications@github.com>:
>Hi
>
>Jup ist eingetragen, der kumulierte Wert und Tagesanfang wird auch
>geschrieben aber die anderen Werte (seit Tages Anfang usw) alle nicht
>
>![Image](https://i.imgur.com/elzlXFe.jpg)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hdering/homematic_verbrauchszaehler/issues/9#issuecomment-381364841

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DutchmanNL** [comment]
Eindeutig true 

![Image](https://i.imgur.com/sOkgjzv.jpg)

**Comment by DutchmanNL** [comment]
könntest es eventuell doch mit der "kilo" Veränderung zu tun haben, im forum hat jemand keine Problemen ohne diesen wert.

https://forum.iobroker.net/viewtopic.php?f=21&t=12272&p=142728#p142728

**Comment by hdering** [comment]
Ich denke ich weiß woran es liegt. Hast du im allgemeinen Arbeitspreis etwas eingetragen?

Strom.Preis.aktuell.Arbeitspreis. ?

Wenn dort 0 steht, dann trag dort Mal etwas über 0 ein, z.b. 0.26



Am 15. April 2018 11:51:56 MESZ schrieb Dutchman <notifications@github.com>:
>könntest es eventuell doch mit der "kilo" Veränderung zu tun haben, im
>forum hat jemand keine Problemen ohne diesen wert.
>
>https://forum.iobroker.net/viewtopic.php?f=21&t=12272&p=142728#p142728
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hdering/homematic_verbrauchszaehler/issues/9#issuecomment-381393855

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DutchmanNL** [comment]
ich hatte dort nicht eingetragen jetzt ergänzt mit 0.26.

der wert “Verbrauch seit Tagesbeginn (Stroom_Levering_Dal)” und “Stromkosten heute (Stroom_Levering_Dal)” bleiben aber trotzdem auf 0 stehen.

“Zählerstand Tagesbeginn (Stroom_Levering_Dal)” wurde um 00:00 Uhr richtig gefüllt.


On 15 Apr 2018, at 12:03, hdering <notifications@github.com<mailto:notifications@github.com>> wrote:

0.26

**Comment by hdering** [comment]
Warte Mal, bis  ein neuer Wert reinkommt.

Am 15. April 2018 12:10:15 MESZ schrieb Dutchman <notifications@github.com>:
>ich hatte dort nicht eingetragen jetzt ergänzt mit 0.26.
>
>der wert “Verbrauch seit Tagesbeginn (Stroom_Levering_Dal)” und
>“Stromkosten heute (Stroom_Levering_Dal)” bleiben aber trotzdem auf 0
>stehen.
>
>“Zählerstand Tagesbeginn (Stroom_Levering_Dal)” wurde um 00:00 Uhr
>richtig gefüllt.
>
>
>On 15 Apr 2018, at 12:03, hdering
><notifications@github.com<mailto:notifications@github.com>> wrote:
>
>0.26
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hdering/homematic_verbrauchszaehler/issues/9#issuecomment-381394931

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DutchmanNL** [comment]
ich bekommen all 10 sec - 1 min neue werten vom zähler :)
ist kein Hm Sensor sondern digitaler Strommesser vom Netzbetreiber welche ich mit dem smarter adapter lese

**Comment by hdering** [comment]
Hol dir mal das aktuelle Skript, ich hatte noch einen kleinen Fehler (den den du hast).

Am 15. April 2018 12:23:11 MESZ schrieb Dutchman <notifications@github.com>:
>mit dem füllen der variable kommt jetzt aber ein Fehler :
>
>Error in callback: ReferenceError: enable_Grundpreis is not defined
>at berechneVerbrauchUndKosten
>(script.js.VerbruikLogging.Stroomverbruik_Meter_new:573:8)
>at run (script.js.VerbruikLogging.Stroomverbruik_Meter_new:399:13)
>at Object. (script.js.VerbruikLogging.Stroomverbruik_Meter_new:226:25)
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hdering/homematic_verbrauchszaehler/issues/9#issuecomment-381395580

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DutchmanNL** [comment]
habe jetzt 1.3.1 drauf und die werte werden aktualisiert ! erstes erfolgt Erlebnis, bekomme jetzt aber minus werte

![screen shot 2018-04-15 at 12 33 08](https://user-images.githubusercontent.com/7318445/38777501-3485a5fe-40a9-11e8-9567-094ef613e093.png)

**Comment by DutchmanNL** [comment]
mein Fehler, ich hatte kilo auf false stehen es funktioniert jetzt !!!

**Comment by hdering** [comment]
Sehr gut. Ich werde morgen eine neue Version online stellen, die dein Problem abfängt

Am 15. April 2018 12:34:48 MESZ schrieb Dutchman <notifications@github.com>:
>mein Fehler, ich hatte kilo auf false stehen es funktioniert jetzt !!!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hdering/homematic_verbrauchszaehler/issues/9#issuecomment-381396146

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DutchmanNL** [comment]
super danke !

**Comment by hdering** [comment]
1.3.3 (2018-04-16)
(hdering) Wenn Standard Arbeitspreis 0 war, egal ob eigenerPreis aktiviert war, wurde Verbrauch und Kosten nicht berechnet
